tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "mongodb/brew"

brew "memcached"
brew "postgresql"
brew "mysql"
brew "asdf"
brew "redis"
brew "mongodb-community@6.0"
brew "asdf"
brew "diff-so-fancy"
brew "git-extras"
brew "jless"
