tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/services"

brew "memcached"
brew "postgresql"
brew "mysql"
brew "redis"
brew "diff-so-fancy"
brew "git-extras"
brew "jless"
brew "todoist-cli"
